name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - plotnine
    - statsmodels
  - rpy2
  - r-base=3.6.1
  - r-rcpp
  - r-tidyverse
  - r-lme4
  - r-irkernel